wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    code_path: code/bert_feature_extraction_classification/main.py
    framework: huggingface
    huggingface_version: 4.18.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1651213057
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      3:
      - 13
      4: 3.8.10
      5: 0.12.15
      6: 4.18.0
      8:
      - 5
